api_login_check:
  path: /api/login_check

home:
  path: /home

registration:
  path: /registration

app_logout:
  path: /logout

details_book:
  path: '/books/{id}'
  controller: 'App\Controller\BookController::detailsBook'