api_login_check:
  path: /api/login_check

home:
  path: /home

registration:
  path: /registration

app_logout:
  path: /logout

details_book:
  path: /books/{id}
  controller: App\Controller\BookController::detailsBook
  
save_comment:
  path: /books/{id}/comments
  controller: App\Controller\BookController::saveComment

form_to_update_comment:
  path: /books/{id_book}/comments/{id}/update
  controller: App\Controller\BookController::form_to_update_comment

update_comment:
  path: /books/{id_book}/comments/{id}
  controller: App\Controller\BookController::editComment